name: Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  all:
    permissions:
      contents: write
    name: All

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          platform: windows-64
        - target: i686-pc-windows-msvc
          os: windows-latest
          platform: windows-32
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          platform: windows-arm64

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v6

    - name: Check Tag
      id: check-tag
      shell: bash
      run: |
        ver=${GITHUB_REF##*/}
        echo "version=$ver" >> $GITHUB_OUTPUT
        if [[ "$ver" =~ [0-9]+.[0-9]+.[0-9]+$ ]]; then
          echo "rc=false" >> $GITHUB_OUTPUT
        else
          echo "rc=true" >> $GITHUB_OUTPUT
        fi


    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Show Version Information (Rust, cargo, GCC)
      shell: bash
      run: |
        gcc --version || true
        rustup -V
        rustup toolchain list
        rustup default
        cargo -V
        rustc -V
      
    - name: Build
      shell: bash
      run: cargo build --locked --release --target=${{ matrix.target }}

    - name: Build Archive
      shell: bash
      id: package
      env:
        target: ${{ matrix.target }}
        platform: ${{ matrix.platform }}
        version:  ${{ steps.check-tag.outputs.version }}
      run: |
        set -euxo pipefail

        bin=${GITHUB_REPOSITORY##*/}
        dist_dir=`pwd`/dist
        name=$bin-$version-$platform
        executable=target/$target/release/$bin

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          executable=$executable.exe
        fi

        mkdir $dist_dir
        cp $executable window-switcher.ini README.md LICENSE $dist_dir
        cd $dist_dir

        if [[ "$RUNNER_OS" == "Windows" ]]; then
            archive=$name.zip
            7z a $archive window-switcher.exe window-switcher.ini README.md LICENSE
            sha256sum $archive > $archive.sha256
            echo "archive=dist/$archive" >> $GITHUB_OUTPUT
            echo "checksum=dist/$archive.sha256" >> $GITHUB_OUTPUT
        else
            archive=$name.tar.gz
            tar -czf $archive *
            sha256sum $archive > $archive.sha256
            echo "archive=dist/$archive" >> $GITHUB_OUTPUT
            echo "checksum=dist/$archive.sha256" >> $GITHUB_OUTPUT
        fi

    - name: Publish Archive
      uses: softprops/action-gh-release@v2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        body_path: CHANGELOG.md
        files: |
          ${{ steps.package.outputs.archive }}
          ${{ steps.package.outputs.checksum }}
        prerelease: ${{ steps.check-tag.outputs.rc == 'true' }}
